# Internal helper: resolve extdata directory from install or source checkout.
cmm_normalize_extdata_dir <- function(extdata_dir = NULL) {
  if (!is.null(extdata_dir)) {
    return(normalizePath(extdata_dir, mustWork = TRUE))
  }

  installed <- system.file("extdata", package = "curatedMicrobiomeMetabolomeData")
  if (nzchar(installed) && dir.exists(installed)) {
    return(installed)
  }

  checkout <- file.path(getwd(), "inst", "extdata")
  if (dir.exists(checkout)) {
    return(normalizePath(checkout, mustWork = TRUE))
  }

  stop(
    "Could not locate package data. ",
    "Run `Rscript data-raw/format_study_data.R` in the repository root ",
    "or pass `extdata_dir` explicitly."
  )
}

# Internal helper: read csv/csv.gz with stable defaults.
cmm_read_csv_any <- function(path) {
  if (!file.exists(path)) {
    stop("File does not exist: ", path)
  }

  con <- if (grepl("\\.gz$", path, ignore.case = TRUE)) {
    gzfile(path, open = "rt")
  } else {
    file(path, open = "rt")
  }
  on.exit(close(con), add = TRUE)

  utils::read.csv(
    con,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )
}

#' Study Index for Curated Microbiome-Metabolome Data
#'
#' Read the study index generated by `data-raw/format_study_data.R`.
#'
#' @param extdata_dir Optional explicit path to the package `extdata` directory.
#'
#' @return A `data.frame` with one row per study and modality file metadata.
#' @export
cmm_study_index <- function(extdata_dir = NULL) {
  extdata_dir <- cmm_normalize_extdata_dir(extdata_dir)
  index_path <- file.path(extdata_dir, "study_index.csv")
  if (!file.exists(index_path)) {
    stop("Missing study index: ", index_path)
  }

  utils::read.csv(
    index_path,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )
}

#' List Available Studies
#'
#' @inheritParams cmm_study_index
#'
#' @return Character vector of study identifiers.
#' @export
cmm_studies <- function(extdata_dir = NULL) {
  unique(cmm_study_index(extdata_dir = extdata_dir)$study)
}

#' List Available Modalities for a Study
#'
#' @inheritParams cmm_study_index
#' @param study Study identifier (for example `"FranzosaE_2019"`).
#'
#' @return Character vector chosen from `metadata`, `species`, `metabolome`.
#' @export
cmm_available_modalities <- function(study, extdata_dir = NULL) {
  index <- cmm_study_index(extdata_dir = extdata_dir)
  row <- index[index$study == study, , drop = FALSE]
  if (nrow(row) == 0) {
    stop("Unknown study: ", study)
  }

  modalities <- c("metadata", "species", "metabolome")
  flags <- vapply(
    modalities,
    function(x) isTRUE(row[[paste0("has_", x)]][1]),
    logical(1)
  )

  modalities[flags]
}

#' Load a Single Modality for One Study
#'
#' @inheritParams cmm_study_index
#' @param study Study identifier.
#' @param modality One of `metadata`, `species`, `metabolome`.
#' @param allow_missing If `TRUE`, return `NULL` when modality is missing.
#'
#' @return A `data.frame` or `NULL` if missing and `allow_missing = TRUE`.
#' @export
cmm_load_modality <- function(
  study,
  modality = c("metadata", "species", "metabolome"),
  extdata_dir = NULL,
  allow_missing = FALSE
) {
  modality <- match.arg(modality)
  index <- cmm_study_index(extdata_dir = extdata_dir)
  row <- index[index$study == study, , drop = FALSE]
  if (nrow(row) == 0) {
    stop("Unknown study: ", study)
  }

  file_col <- paste0(modality, "_file")
  rel_path <- row[[file_col]][1]
  if (!nzchar(rel_path)) {
    if (allow_missing) {
      return(NULL)
    }
    stop("No ", modality, " file available for study ", study)
  }

  path <- file.path(cmm_normalize_extdata_dir(extdata_dir), rel_path)
  cmm_read_csv_any(path)
}

#' Load Curated Data for One Study
#'
#' @inheritParams cmm_study_index
#' @param study Study identifier.
#' @param modalities Character vector of modalities to load.
#' @param drop_missing If `TRUE`, missing modalities are omitted from output.
#'
#' @return Named list of `data.frame` objects.
#' @export
cmm_load_study <- function(
  study,
  modalities = c("metadata", "species", "metabolome"),
  extdata_dir = NULL,
  drop_missing = TRUE
) {
  modalities <- match.arg(
    modalities,
    choices = c("metadata", "species", "metabolome"),
    several.ok = TRUE
  )

  loaded <- stats::setNames(vector("list", length(modalities)), modalities)
  for (modality in modalities) {
    loaded[[modality]] <- cmm_load_modality(
      study = study,
      modality = modality,
      extdata_dir = extdata_dir,
      allow_missing = drop_missing
    )
  }

  if (drop_missing) {
    loaded <- loaded[!vapply(loaded, is.null, logical(1))]
  }

  loaded
}

#' Curated Microbiome-Metabolome Data Accessor
#'
#' Main convenience loader inspired by `curatedMetagenomicData`.
#'
#' @inheritParams cmm_study_index
#' @param studies Optional character vector of studies to load. Defaults to all.
#' @param modalities Character vector of modalities to load.
#' @param drop_missing If `TRUE`, missing modalities are omitted per study.
#'
#' @return Named list keyed by study, where each element is a modality list.
#' @export
curatedMicrobiomeMetabolomeData <- function(
  studies = NULL,
  modalities = c("metadata", "species", "metabolome"),
  extdata_dir = NULL,
  drop_missing = TRUE
) {
  index <- cmm_study_index(extdata_dir = extdata_dir)
  all_studies <- unique(index$study)

  if (is.null(studies)) {
    studies <- all_studies
  }

  unknown <- setdiff(studies, all_studies)
  if (length(unknown) > 0) {
    stop("Unknown study/studies: ", paste(unknown, collapse = ", "))
  }

  out <- stats::setNames(vector("list", length(studies)), studies)
  for (study in studies) {
    out[[study]] <- cmm_load_study(
      study = study,
      modalities = modalities,
      extdata_dir = extdata_dir,
      drop_missing = drop_missing
    )
  }

  out
}

